# Generated by Django 6.0.6 on 2026-07-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_alter_case_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_status',
            field=models.CharField(choices=[('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('WAITING_REPORT', 'Waiting for Report'), ('PENDING_REVIEW', 'Pending Review'), ('CLOSED', 'Closed')], default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('WAITING_REPORT', 'Waiting for Report'), ('PENDING_REVIEW', 'Pending Review'), ('CLOSED', 'Closed')], default='NEW', max_length=20),
        ),
    ]
