# Generated by Django 6.0.6 on 2026-07-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_alter_case_case_status_alter_case_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='asset_tag',
            field=models.CharField(blank=True, default='', help_text='Machine identifier e.g. CL3-PC01', max_length=50),
        ),
    ]
