# Generated by Django 6.0.6 on 2026-07-09 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_reportimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseauditlog',
            name='related_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='cases.casenote'),
        ),
    ]
