from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden, JsonResponse
from django.core.paginator import Paginator
from django.db.models import Q
from django.utils import timezone
from django.contrib import messages
from datetime import timedelta
import json

from .models import ActivityLog, Feedback


def _is_admin(user):
    return user.is_superuser or user.groups.filter(name__in=['admin']).exists()


@login_required
def log_list(request):
    if not _is_admin(request.user):
        return HttpResponseForbidden("You do not have permission to access this page.")

    queryset = ActivityLog.objects.select_related('user').all()

    search_query = request.GET.get('search', '').strip()
    if search_query:
        queryset = queryset.filter(
            Q(user__identifier__icontains=search_query) |
            Q(description__icontains=search_query) |
            Q(action__icontains=search_query)
        )

    action_filter = request.GET.get('action', '')
    if action_filter:
        queryset = queryset.filter(action=action_filter)

    date_from = request.GET.get('date_from', '')
    if date_from:
        queryset = queryset.filter(timestamp__date__gte=date_from)

    date_to = request.GET.get('date_to', '')
    if date_to:
        queryset = queryset.filter(timestamp__date__lte=date_to)

    paginator = Paginator(queryset, 20)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    actions = ActivityLog.ACTION_CHOICES

    context = {
        'page_obj': page_obj,
        'search_query': search_query,
        'action_filter': action_filter,
        'date_from': date_from,
        'date_to': date_to,
        'actions': actions,
    }
    return render(request, 'logs/log_list.html', context)


@login_required
def log_download(request):
    if not _is_admin(request.user):
        return HttpResponseForbidden("You do not have permission to access this page.")

    queryset = ActivityLog.objects.select_related('user').all()

    action_filter = request.GET.get('action', '')
    if action_filter:
        queryset = queryset.filter(action=action_filter)

    date_from = request.GET.get('date_from', '')
    if date_from:
        queryset = queryset.filter(timestamp__date__gte=date_from)

    date_to = request.GET.get('date_to', '')
    if date_to:
        queryset = queryset.filter(timestamp__date__lte=date_to)

    logs_data = []
    for log in queryset[:1000]:
        logs_data.append({
            'timestamp': log.timestamp.isoformat(),
            'user': log.user.identifier if log.user else None,
            'action': log.get_action_display(),
            'action_code': log.action,
            'description': log.description,
            'ip_address': log.ip_address,
        })

    format_type = request.GET.get('format', 'json')

    if format_type == 'txt':
        response = HttpResponse(content_type='text/plain')
        response['Content-Disposition'] = f'attachment; filename="activity_logs_{timezone.now().strftime("%Y%m%d_%H%M%S")}.txt"'

        lines = ["=" * 80]
        lines.append("ACTIVITY LOGS")
        lines.append(f"Generated: {timezone.now().strftime('%Y-%m-%d %H:%M:%S')}")
        lines.append(f"Generated by: {request.user.identifier}")
        lines.append("=" * 80)
        lines.append("")

        for log in logs_data:
            lines.append(f"[{log['timestamp']}]")
            lines.append(f"  User: {log['user'] or 'System'}")
            lines.append(f"  Action: {log['action']}")
            lines.append(f"  Description: {log['description']}")
            lines.append(f"  IP: {log['ip_address'] or 'N/A'}")
            lines.append("-" * 40)

        response.write('\n'.join(lines))
    else:
        response = JsonResponse({
            'generated_at': timezone.now().isoformat(),
            'generated_by': request.user.identifier,
            'count': len(logs_data),
            'logs': logs_data
        }, json_dumps_params={'indent': 2})
        response['Content-Disposition'] = f'attachment; filename="activity_logs_{timezone.now().strftime("%Y%m%d_%H%M%S")}.json"'

    return response


@login_required
def feedback_submit(request):
    if request.method == 'POST':
        feedback_type = request.POST.get('type', '')
        title = request.POST.get('title', '').strip()
        description = request.POST.get('description', '').strip()

        if not title or not description:
            messages.error(request, "Title and description are required.")
            return redirect('feedback_submit')

        if feedback_type not in ['BUG', 'FEATURE']:
            messages.error(request, "Invalid feedback type.")
            return redirect('feedback_submit')

        Feedback.objects.create(
            type=feedback_type,
            title=title,
            description=description,
            submitted_by=request.user,
        )
        messages.success(request, "Your feedback has been submitted. Thank you!")
        return redirect('dashboard')

    return render(request, 'logs/feedback_submit.html')


@login_required
def feedback_list(request):
    if not _is_admin(request.user):
        return HttpResponseForbidden("You do not have permission to access this page.")

    queryset = Feedback.objects.select_related('submitted_by').all()

    search_query = request.GET.get('search', '').strip()
    if search_query:
        queryset = queryset.filter(
            Q(title__icontains=search_query) |
            Q(description__icontains=search_query) |
            Q(submitted_by__identifier__icontains=search_query)
        )

    type_filter = request.GET.get('type', '')
    if type_filter:
        queryset = queryset.filter(type=type_filter)

    status_filter = request.GET.get('status', '')
    if status_filter:
        queryset = queryset.filter(status=status_filter)

    paginator = Paginator(queryset, 20)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'search_query': search_query,
        'type_filter': type_filter,
        'status_filter': status_filter,
        'type_choices': Feedback.TYPE_CHOICES,
        'status_choices': Feedback.STATUS_CHOICES,
    }
    return render(request, 'logs/feedback_list.html', context)


@login_required
def feedback_detail(request, feedback_id):
    if not _is_admin(request.user):
        return HttpResponseForbidden("You do not have permission to access this page.")

    feedback = get_object_or_404(Feedback, id=feedback_id)

    if request.method == 'POST':
        status = request.POST.get('status', '')
        admin_response = request.POST.get('admin_response', '').strip()

        if status in dict(Feedback.STATUS_CHOICES):
            feedback.status = status
        feedback.admin_response = admin_response
        feedback.save()
        messages.success(request, "Feedback updated.")
        return redirect('feedback_detail', feedback_id=feedback.id)

    context = {
        'feedback': feedback,
    }
    return render(request, 'logs/feedback_detail.html', context)
