# Generated by Django 6.0.6 on 2026-07-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_issuetemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['grid_row', 'grid_col']},
        ),
        migrations.AddField(
            model_name='lab',
            name='grid_columns',
            field=models.IntegerField(default=8, help_text='Number of columns in the floor grid'),
        ),
        migrations.AddField(
            model_name='machine',
            name='grid_col',
            field=models.IntegerField(default=0, help_text='Column position in grid (0-indexed)'),
        ),
        migrations.AddField(
            model_name='machine',
            name='grid_row',
            field=models.IntegerField(default=0, help_text='Row position in grid (0-indexed)'),
        ),
    ]
